# settings for website
project:
  type: website
  
  preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true
  
  output-dir: docs

website:
  title: "Lucas Watson"
  # favicon: "/files/photos/my_favicon.png"
  
  
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



